### ISSUE TITLE
Information is not complete

### ISSUE THREAD

**Issue by ankitkumarsr** [wililupy/ubuntu-onie#1]
Please provide assumption part of process How to run HTTP server on Qemu on Ubuntu

**Comment by wililupy** [comment]
Excellent point. 
I run lighttpd on my qemu server and leave my ONIE images in the /var/www directory.

**Comment by mariusz-stordis** [comment]
Installation step failed: The falling step is: Install the GRUB boot loader on hardisk

**Comment by wililupy** [comment]
No reply so assuming it's closed.
